name: 賀屋 悠
name_en: Haruka Kaya
site_title: 賀屋 悠 | ものづくりと好きなこと
site_title_en: Haruka Kaya | Things I make and enjoy
github: https://github.com/Haruka-Kaya
email: kayaharuka@hotmail.com
twitter: https://x.com/HarukaKayaDev
hackerone: https://hackerone.com/haruka-kaya
